name: Notify Slack on Update with File Details

on:
  push:
    branches:
      - main

jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          FILES_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          if [ -z "$FILES_CHANGED" ]; then
            FILES_MSG="No files changed."
          else
            FILES_MSG="Files changed:\n\`\`\`$FILES_CHANGED\`\`\`"
          fi
          
          PAYLOAD=$(cat <<EOF
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "A new push to the *main* branch has occurred. Check out the GitHub repository for more details."
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "$FILES_MSG"
                }
              }
            ]
          }
EOF
          )
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
