name: Notify Slack on Update

on:
  push:
    branches:
      - main

jobs:
  notifySlack:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: '{"text":"Git push done in the repo, CyberSec"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
