name: Notify Slack on Update with File Details

on:
  push:
    branches:
      - main

jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Changed Files
        id: get_files
        run: |
          echo "::set-output name=files_changed::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})"
        shell: bash

      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          FILES_CHANGED: ${{ steps.get_files.outputs.files_changed }}
        run: |
          if [ -z "${FILES_CHANGED}" ]; then
            FILES_MSG="No files changed."
          else
            FILES_MSG="Files changed: ${FILES_CHANGED}"
          fi
          PAYLOAD="{
            \"text\": \"A new push to the main branch has occurred. ${FILES_MSG} Check out the GitHub repository for more details.\"
          }"
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL
