jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: '{"text":"Git push done in the repo , CyberSec"}'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
