name: Notify Slack on Update with File Details and Link

on:
  push:
    branches:
      - main

jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_REPOSITORY_URL: https://github.com/${{ github.repository }}
        run: |
          git fetch --depth=2 origin ${{ github.ref }}
          
          FIRST_FILE_CHANGED=$(git diff --name-only HEAD~1 HEAD | head -n 1)
          if [ -z "$FIRST_FILE_CHANGED" ]; then
            FILES_MSG="No files changed."
            FIRST_FILE_URL=""
            VIEW_CHANGES_SECTION=""
          else
            FILES_CHANGED_LIST=$(git diff --name-only HEAD~1 HEAD | awk '{print "- " $0}')
            FIRST_FILE_URL="$GITHUB_REPOSITORY_URL/blob/${{ github.sha }}/$FIRST_FILE_CHANGED"
            FILES_MSG="*Files changed:*\n\`\`\`${FILES_CHANGED_LIST}\`\`\`"
            VIEW_CHANGES_SECTION=", {\"type\": \"section\", \"text\": {\"type\": \"mrkdwn\", \"text\": \"<${FIRST_FILE_URL}|View changes>\"}}"
          fi
          
          COMMIT_MSG=$(git log -1 --pretty=%B)
          COMMITTER_NAME=$(git log -1 --pretty=%cn)
          COMMIT_DATE=$(git log -1 --pretty=%cd)
          
          PAYLOAD=$(echo -n "{
            \"blocks\": [
              {
                \"type\": \"header\",
                \"text\": {
                  \"type\": \"plain_text\",
                  \"text\": \"📢 New Update in ${GITHUB_REPOSITORY}\",
                  \"emoji\": true
                }
              },
              {
                \"type\": \"section\",
                \"text\": {
                  \"type\": \"mrkdwn\",
                  \"text\": \"A new push to the *main* branch by *${COMMITTER_NAME}* has occurred.\n\n*Commit Message:* ${COMMIT_MSG}\n*Date:* ${COMMIT_DATE}\n\n${FILES_MSG}\"
                }
              }
              ${VIEW_CHANGES_SECTION}
            ]
          }" | jq -c .)
          
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK_URL

